Task2:Adding  instant search
snehaSaraJohn/tmo-web-ui-developer-puzzle pull request #2
Opened 2023-11-11 09:51 UTC by snehaSaraJohn

2023-11-12 17:00 UTC, SiddhuJajoo requested changes

2023-11-12 17:00 UTC, SiddhuJajoo commented on web-puzzle-tmo-master/apps/okreads-e2e/src/integration/search-books.spec.ts
> +    cy.get('input[type="search"]').type('angular');
Above testcase and this is same. No need to add this, just update title of above one .

2023-11-12 17:00 UTC, SiddhuJajoo commented on web-puzzle-tmo-master/libs/books/feature/src/lib/book-search/book-search.component.spec.ts
> +    it('searchBooks() should be called when we have value for search term and actual time spent after entering search term is equal to 500ms', fakeAsync(() => {
Keep it simple as `should dispatch searchBooks action to retrieve book details when search term is typed`

2023-11-12 17:00 UTC, SiddhuJajoo commented on web-puzzle-tmo-master/libs/books/feature/src/lib/book-search/book-search.component.spec.ts
>        discardPeriodicTasks();
Add testcase for `clearSearch` action

2023-11-13 11:17 UTC, snehaSaraJohn commented on web-puzzle-tmo-master/apps/okreads-e2e/src/integration/search-books.spec.ts
> +    cy.get('input[type="search"]').type('angular');
Resolved

2023-11-13 11:17 UTC, snehaSaraJohn commented on web-puzzle-tmo-master/libs/books/feature/src/lib/book-search/book-search.component.spec.ts
> +    it('searchBooks() should be called when we have value for search term and actual time spent after entering search term is equal to 500ms', fakeAsync(() => {
Resolved

2023-11-17 01:48 UTC, SiddhuJajoo reviewed
All changes should be squashed

2023-11-17 01:48 UTC, SiddhuJajoo commented on web-puzzle-tmo-master/libs/books/feature/src/lib/book-search/book-search.component.ts
>    addBookToReadingList(book: Book):void {
Are you using this searchBooks() anywhere? Is this really needed?

2023-11-17 14:34 UTC, snehaSaraJohn commented on web-puzzle-tmo-master/libs/books/feature/src/lib/book-search/book-search.component.ts
>    addBookToReadingList(book: Book):void {
I used that inside function
 
  searchExample() :void{
    this.searchForm.controls.term.setValue('javascript');
    this.searchBooks();
  }

, Now i changed code such a way that we can eliminate this unnecessary function

2023-11-20 12:40 UTC, closed without merging